language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
    - phpenv config-rm xdebug.ini
    - if [[ "$TRAVIS_PHP_VERSION" == 5.* ]]; then echo 'extension=mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
    - if [[ "$TRAVIS_PHP_VERSION" == 7.* ]]; then
        echo 'extension=mongodb.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; composer require "alcaeus/mongo-php-adapter"  --ignore-platform-reqs;
      fi
    - composer install --dev

services:
    - mongodb